### PR TITLE
Include development environment setup instructions in readme

### PR DESCRIPTION
**Pull request by avanzzzi**
As I was going through these steps, I decided to update the readme. Perhaps the ideal is to merge this only after the current prism branches are finalized.

### CODE REVIEW

**Review by scottcorgan — APPROVED** [review]

**Comment by prodz18** [comment]
This is great! There's a couple of additional steps in Supabase regarding triggers and functions but I can add those in another PR. Thanks for this!

**Comment by avanzzzi** [comment]
> This is great! There's a couple of additional steps in Supabase regarding triggers and functions but I can add those in another PR. Thanks for this!

I did not include the steps related to seeding the DB because of the steps needed to get the user ID from auth in supabase and change the current seed. If you think it's a good idea, I can include this steps as well.

**Comment by prodz18** [comment]
Yep, we should include them. I can send you those steps so you can test/try it yourself and then add them here. I'll post them discord and tag you. Let's leave this PR open until we have those remaining steps.

**Comment by prodz18** [comment]
Hey @avanzzzi , here's the steps for creating the trigger and function in supabase:

# Setup Triggers & Functions in Supabase


## CREATE A NEW FUNCTION
1. From the left side panel, select `Database`
2. Select `Functions` and click `Create a new function`
3. Enter the following:
- **Name of function**: can be anything
- **Schema**: select `public`
- **Return** type: select `trigger`
- **Definition**: enter the following:

```
begin
  insert into public."Profile"(id)
  values(new.id);
  return new;
end;
```

- Click on `Show advanced settings`
- Select `SECURITY DEFINER`
- Click `Confirm`

## CREATE A TRIGGER
1. Select `Triggers` from the same previous list
2. Select `Create a new trigger`
3. Enter the following:
- **Name of trigger**: can be anything
- **Table**: select `users auth`
- **Events**: select `Insert`
- **Trigger type**: select `After the event`
- **Orientation**: select `Row`
- **Function to trigger**:  select the newly created Function from the steps above
- Click `Confirm`

**Comment by prodz18** [comment]
Also: add  a **Troubleshooting** section.

You can add this to that section:

We need to do a `npm run generateTypes` every time there's changes in the Schemas. Otherwise you'll get an error that Prisma cannot find certain properties and types.

**Comment by avanzzzi** [comment]
Done!

**Review by prodz18 — CHANGES_REQUESTED** [review]

**Review by prodz18 — APPROVED** [review]

**Pull request merged**
